version: '3'

services:
  web:
    image: php:7.4-apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./build:/var/www/html
      - ./apache/demo.apache.conf:/etc/apache2/sites-enabled/demo.conf
